language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
services:
  - redis-server
before_install:
  # install phpredis extension.
  - git clone --depth=50 https://github.com/nicolasff/phpredis
  - sh -c "cd phpredis && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" > redis.ini && phpenv config-add redis.ini
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100

after_script:
  - php vendor/bin/coveralls -v
