language: php
php:
  - 7.0
  - 5.6
  - 5.5
services:
  - redis-server
before_install:
  - ./.travis_redis.sh
before_script:
  - composer install
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100

after_script:
  - php vendor/bin/php-coveralls -v
