language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
services:
  - redis-server
before_install:
  # install phpredis extension.
  - wget -O phpredis.tar.gz --no-check-certificate https://github.com/nicolasff/phpredis/tarball/master
  - tar -xzf phpredis.tar.gz
  - sh -c "cd nicolasff-phpredis-* && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" > redis.ini && phpenv config-add redis.ini
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100

after_script:
  - php vendor/bin/coveralls -v
